export const ActionTypes = {
  ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',

  INCREASE_PRODUCTS_TO_CART: 'INCREASE_PRODUCTS_TO_CART',

  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL'
};
