export const ActionTypes = {
  ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',
  INCREASE_PRODUCTS_TO_CART: 'INCREASE_PRODUCTS_TO_CART',
  DECREASE_PRODUCTS_TO_CART: 'DECREASE_PRODUCTS_TO_CART',
  REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
  SUM_CART_VALUE_TOTAL: 'SUM_CART_VALUE_TOTAL',

  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL'
};
